kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /jenkins
        backend:
          serviceName: cd-jenkins
          servicePort: 8080
