kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: client-integration
spec:
  replicas: 1
  template:
    metadata:
      name: client
      labels:
        app: client
        env: integration
    spec:
      containers:
      - name: client
        image: gcr.io/silent-vim-243301/client:1.0.0
        resources:
          limits:
            # At the moment we are limiting our application to this much, we shouldn't have to deal with that much load on integration no matter what
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        env:
          - name: REACT_APP_API_KEY
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: apiKey
          - name: REACT_APP_AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: authDomain
          - name: REACT_APP_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: databaseURL
          - name: REACT_APP_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: projectId
          - name: REACT_APP_STORAGE_BUCKET
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: storageBucket
          - name: REACT_APP_MESSAGING_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: messagingSenderId
          - name: REACT_APP_APP_ID
            valueFrom:
              secretKeyRef:
                name: integration-firebase-secret
                key: appId
          # TODO a readiness probe here would be a good touch
          # readinessProbe:
          # httpGet:
          # path: /healthz
          # port: 80
        ports:
          - name: client
            containerPort: 5000
